server:
  # Liberty had httpPort=9080 and httpsPort=9443.
  # We'll run HTTPS on 9443 and add an extra HTTP connector on 9080 via a bean (this is create as a configuration in the file `src/main/java/com/ibm/daytrader/config/DualPortConfig.java`)
  port: 9443
  servlet:
    context-path: /daytrader

  # This is for the keystore setting
  # <keyStore id="defaultKeyStore" password="yourPassword" />
  # TODO: You'll need to create the keystore file at src/main/resources/keystore.p12
  # Use `keytool` to create the keystore:
  # keytool -genkey -alias defaultKeyStore -keyalg RSA -keystore src/main/resources/keystore.p12 -storetype PKCS12 -storepass yourPassword
  ssl:
    enabled: false
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: yourPassword   # match your Liberty <keyStore ... password="..."/>

spring:
  application:
    name: daytrader
  datasource:
    url: jdbc:h2:file:./data/tradedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    hikari:
      maximum-pool-size: 100          # Liberty maxPoolSize="100"
      minimum-idle: 100               # Liberty minPoolSize="100"
      # Liberty isolationLevel="TRANSACTION_READ_COMMITTED"
      transaction-isolation: TRANSACTION_READ_COMMITTED

  # Replace wasJmsServer/Client with embedded Artemis for dev
  artemis:
    mode: embedded
    embedded:
      enabled: true

logging:
  level:
    com.ibm.daytrader: DEBUG  # Not sure what "daytrader=fine" means from a logging perspective, so I am setting this default.

# Map Liberty server.env
daytrader:
  max-quotes: ${MAX_QUOTES:1000}
  max-users: ${MAX_USERS:500}
